// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my FinWise profile",
  description: "Fetch the signed-in user's FinWise profile: name, phone, date of birth, address, occupation, income range and investments.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("full_name, phone_number, date_of_birth, address, occupation, income_range, investments, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found for this user." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/update-profile.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";
var update_profile_default = defineTool2({
  name: "update_profile",
  title: "Update my FinWise profile",
  description: "Update fields on the signed-in user's FinWise profile. Only the provided fields are changed.",
  inputSchema: {
    full_name: z.string().trim().nullable().optional().describe("Full name"),
    phone_number: z.string().trim().nullable().optional().describe("Phone number"),
    address: z.string().trim().nullable().optional().describe("Postal address"),
    occupation: z.string().trim().nullable().optional().describe("Occupation"),
    income_range: z.string().trim().nullable().optional().describe("Annual income range, e.g. '5-10 LPA'")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const updates = Object.fromEntries(
      Object.entries(input).filter(([, value]) => value !== void 0)
    );
    if (Object.keys(updates).length === 0) {
      return { content: [{ type: "text", text: "No fields provided to update." }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").update(updates).eq("user_id", ctx.getUserId()).select("full_name, phone_number, address, occupation, income_range").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pcotqipqghcgckjgycxz";
var mcp_default = defineMcp({
  name: "finwise-mcp",
  title: "FinWise",
  version: "0.1.0",
  instructions: "Tools for FinWise, a personal finance app. Use `get_profile` to read the signed-in user's financial profile and `update_profile` to change profile details.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, update_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
